server:
  port: 8080
  error:
    include-message: always

spring:
  profiles:
    active: mysql
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

rag:
  service-url: http://127.0.0.1:8000
  upload-dir: ./uploads
